name: Hodor
favicon: null
layout_spectrum: 0.77413
typography_spectrum: 0.49844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#820b94'
    - '#89877f'
    - '#51433a'
    - '#d59e8e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
