name: Hodor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9e5f57'
    - '#c8998e'
    - '#205080'
    - '#131313'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
